### ISSUE TITLE
Traceback when adding CentOS Stream 9 derivative product to CaC/content

### ISSUE THREAD

**Issue by ggbecker** [mildas/content-test-filtering#23]
`./ctf/content_test_filtering.py pr --rule --output json 7878`
```
Traceback (most recent call last):
  File "/__w/content/content/./ctf/content_test_filtering.py", line 44, in <module>
    diff_structure = diff_analysis.analyse_file(file_record)
  File "/__w/content/content/ctf/ctf/diff_analysis.py", line 54, in analyse_file
    return file_analyzer.process_analysis()
  File "/__w/content/content/ctf/ctf/analysis/OVALAnalysis.py", line 215, in process_analysis
    self.diff_struct.add_changed_product_by_rule(self.rule_name, msg=msg)
  File "/__w/content/content/ctf/ctf/DiffStruct.py", line 122, in add_changed_product_by_rule
    product_name = self.get_rule_products(rule_name)
  File "/__w/content/content/ctf/ctf/DiffStruct.py", line 89, in get_rule_products
    with open(ruleyml_path) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
Error: Process completed with exit code 1.
```

**Comment by ggbecker** [comment]
CTF in verbose:

```
DEBUG   content_test_filtering - Getting files from 'git diff'
DEBUG   diff                   - Cloning repository to /tmp/tmpubp3kqpu directory
DEBUG   diff                   - Fetched to pr-7908 branch
DEBUG   diff                   - Comparing commit 05baabdf048916a543a33c1ca9b37d167692c223 with HEAD of pr-7908
DEBUG   BashAnalysis           - Analyzing bash file linux_os/guide/system/accounts/accounts-banners/gui_login_banner/dconf_gnome_login_banner_text/bash/ubuntu.sh
DEBUG   BashAnalysis           - Rule name: ubuntu
DEBUG   DiffStruct             - rule.yml was not found for ubuntu
Traceback (most recent call last):
  File "/home/ggasparb/workspace/github/content-test-filtering/content_test_filtering.py", line 44, in <module>
    diff_structure = diff_analysis.analyse_file(file_record)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/diff_analysis.py", line 54, in analyse_file
    return file_analyzer.process_analysis()
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/analysis/BashAnalysis.py", line 103, in process_analysis
    self.diff_struct.add_changed_product_by_rule(self.rule_name, msg=msg)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/DiffStruct.py", line 122, in add_changed_product_by_rule
    product_name = self.get_rule_products(rule_name)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/DiffStruct.py", line 89, in get_rule_products
    with open(ruleyml_path) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by ggbecker** [comment]
```
DEBUG   content_test_filtering - Getting files from 'git diff'
DEBUG   diff                   - Cloning repository to /tmp/tmpog0v5fq1 directory
DEBUG   diff                   - Fetched to pr-7878 branch
DEBUG   diff                   - Comparing commit b9c5c007c38f6f1b8522dc9cce22a27f15d93ce0 with HEAD of pr-7878
DEBUG   PythonAnalysis         - Analyzing python file build-scripts/enable_derivatives.py
DEBUG   content_test_filtering - Unknown type of file products/rhel9/CMakeLists.txt. Analysis has not been performed for it.
DEBUG   content_test_filtering - Unknown type of file products/rhel9/product.yml. Analysis has not been performed for it.
DEBUG   content_test_filtering - Unknown type of file shared/applicability/derivatives.yml. Analysis has not been performed for it.
DEBUG   OVALAnalysis           - Analyzing OVAL file shared/checks/oval/installed_OS_is_centos9.xml
DEBUG   OVALAnalysis           - Rule name: checks
DEBUG   DiffStruct             - rule.yml was not found for checks
Traceback (most recent call last):
  File "/home/ggasparb/workspace/github/content-test-filtering/content_test_filtering.py", line 44, in <module>
    diff_structure = diff_analysis.analyse_file(file_record)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/diff_analysis.py", line 54, in analyse_file
    return file_analyzer.process_analysis()
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/analysis/OVALAnalysis.py", line 215, in process_analysis
    self.diff_struct.add_changed_product_by_rule(self.rule_name, msg=msg)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/DiffStruct.py", line 122, in add_changed_product_by_rule
    product_name = self.get_rule_products(rule_name)
  File "/home/ggasparb/workspace/github/content-test-filtering/ctf/DiffStruct.py", line 89, in get_rule_products
    with open(ruleyml_path) as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
